### ISSUE TITLE
Which version of zig does this target?

### ISSUE THREAD

**Issue by ryanschneider** [marler8997/ziglibc#2]
Hi, I just watched your talk about ziglibc, and thought I'd try it out myself as I've been meaning to get back into learning zig.

However, when I try to run `zig build` on the project I'm met w/ the following errors:

```
/Users/ryanschneider/src/ryanschneider/ziglibc/src/trace.zig:6:9: error: pointless discard of function parameter
    _ = args;
        ^~~~
/Users/ryanschneider/src/ryanschneider/ziglibc/src/trace.zig:8:42: note: used here
        std.log.scoped(.trace).info(fmt, args);
                                         ^~~~
/Users/ryanschneider/src/ryanschneider/ziglibc/src/trace.zig:5:9: error: pointless discard of function parameter
    _ = fmt;
        ^~~
/Users/ryanschneider/src/ryanschneider/ziglibc/src/trace.zig:8:37: note: used here
        std.log.scoped(.trace).info(fmt, args);
                                    ^~~
/Users/ryanschneider/src/ryanschneider/ziglibc/src/cstd.zig:671:26: error: invalid builtin function: '@minimum'
    const adjusted_len = @minimum(max_count, size);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm running latest master version of zig (`0.10.0-dev.4476+0f0076666`), but noticed that 0.9.1 has the `@minimum` built-in which was reamed to `@min` in 0.10.x.  As such, I can deduce that this code currently targets 0.9.x, but a) wanted to confirm and b) wanted to suggest that the target version is listed in the read me.

Thanks for doing this project and sharing your progress so far!  Aside: I know I tried building on macOS, which I assume will fail, I was really just curious what sort of error I'd get, but ran into the 0.9/0.10 syntax discrepancies before getting that far.

**Comment by marler8997** [comment]
Glad to year you saw the talk and followed up on it by looking at the project.

Current strategy is to keep up with master, it does look like a couple recent changes came in around `@minimum` being renamed to `@min` and the "pointless discard" errors.  I just pushed a fix for them here: https://github.com/marler8997/ziglibc/commit/d90f40c2c7b3751f36bd7f70f2a0ea8570bfa3f1
